### ISSUE TITLE
[Feature Request] Scout Windows and Mac support 

### ISSUE THREAD

**Issue by Oldes** [airsdk/Adobe-Scout#7]
Just curious, if there will be Scout app available for download without need to have Adobe CC subscription?

**Comment by ajwfrost** [comment]
They already are ..? i.e. like from here:
https://helpx.adobe.com/scout/kb/download-adobe-scout-cc.html

We've got copies of the installers and if they ever take down the page, they have agreed that we can provide them (with the caveat that we need to keep the existing capabilities available for free, like they are now).

**Comment by Oldes** [comment]
Ah, that is good to know. It should be noted in the readme imho. Anyway.. thank you!
