### ISSUE TITLE
Scout is no longer available for download on macOS.

### ISSUE THREAD

**Issue by everseen83** [airsdk/Adobe-Scout#8]
An Adobe agent told me that the app is no longer supported and is not available for download.

As you know, this is an essential app for Air development, so I'd appreciate it if you could provide a link to download it or create a new one.

Thanks.

**Comment by ajwfrost** [comment]
For Windows, temporarily -> https://transfer.harman.com/link/bDrPgCOExKy4bEHTjuJ790
We'll get these set up for download in a more permanent manner shortly...

**Comment by everseen83** [comment]
Thanks for your support.
l looking forward to download it for macOS too.

**Comment by ajwfrost** [comment]
@marchbold would you be able to get these links added into a section in the airsdk.dev site please? We had got Adobe's permission to share these files as-is (on the condition that we didn't charge for them) but probably best that they're hosted by us still...
https://adobe-scout.s3.amazonaws.com/Scout_1_1_3_LREFJC.dmg
https://adobe-scout.s3.amazonaws.com/Scout_1_1_3_LREFJC.msi

thanks

**Comment by marchbold** [comment]
Yep! Will get that added today. I'll publish them as releases in this repository as well.

**Comment by marchbold** [comment]
FYI: https://airsdk.dev/docs/tools/development/scout/getting-started

I've pulled in some existing Adobe documentation, haven't checked through it all but thought it would be a starting point.
